const DEF=[['Dom','Domingo · Cracovia',[['Free tour por Cracovia','Rynek Główny, Kraków',''],['Comer en la zona central','Rynek Główny, Kraków',''],['Tarde: plaza, Planty o Wawel','Wawel Royal Castle, Kraków','']]],['Lun','Lunes · Auschwitz-Birkenau',[['Auschwitz I','Auschwitz-Birkenau Memorial Museum','Entrada reservada y documento de identidad'],['Birkenau (Auschwitz II)','Auschwitz II-Birkenau','']]],['Mar','Martes · Cracovia → Varsovia',[['Tren Cracovia → Varsovia','Kraków Główny railway station',''],['Paseo por el centro de Varsovia','Warsaw Old Town',''],['Parque Łazienki / Ciudad Nueva','Łazienki Park, Warsaw',''],['Calle Nowy Świat','Nowy Świat, Warszawa','']]],['Mié','Miércoles · Varsovia',[['Tour comunista por Varsovia','Palace of Culture and Science, Warsaw',''],['Barrio de Praga','Praga, Warszawa',''],['Tren Varsovia → Cracovia','Warszawa Centralna','Por definir: miércoles noche o jueves temprano']]],['Jue','Jueves · Cracovia',[['Kazimierz','Kazimierz, Kraków',''],['Comer en Starka','Starka Kraków',''],['Podgórze','Podgórze, Kraków',''],['Fábrica de Schindler','Schindler Factory Kraków','']]],['Vie','Viernes · Cracovia',[['Lonja de los Paños','Sukiennice, Kraków',''],['Comer por el centro','Rynek Główny, Kraków',''],['Minas de sal de Wieliczka','Wieliczka Salt Mine','Dentro hace fresco: lleva una capa de abrigo']]],['Sáb','Sábado · Cracovia',[['Día libre','',''],['Cena en Morskie Oko','Morskie Oko restaurante Kraków','']]]];
function makeDays(){return DEF.map((d,di)=>({s:d[0],n:d[1],i:d[2].map((x,k)=>({id:'d'+di+'i'+k,t:x[0],q:x[1],note:x[2]||''}))}))}
let D=makeDays(),done={},day=0,editing=false,armed=null;const LS='viaje-polonia-itinerario-v3',$=x=>document.getElementById(x);
function save(){try{localStorage.setItem(LS,JSON.stringify({D,done,day}))}catch(e){}}
function load(){try{let x=JSON.parse(localStorage.getItem(LS));if(x&&Array.isArray(x.D)&&x.D.length){D=x.D;done=x.done||{};day=Math.min(x.day||0,D.length-1)}}catch(e){}}
function uid(){return'n'+Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function map(q){return'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
const gear='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06a1.7 1.7 0 0 0-1.88-.34 1.7 1.7 0 0 0-1.03 1.56V21h-4v-.08A1.7 1.7 0 0 0 9 19.36a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15 1.7 1.7 0 0 0 3 14H3v-4h.08A1.7 1.7 0 0 0 4.64 9a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6 1.7 1.7 0 0 0 10 3.08V3h4v.08A1.7 1.7 0 0 0 15 4.64a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9 1.7 1.7 0 0 0 20.92 10H21v4h-.08A1.7 1.7 0 0 0 19.4 15Z"/></svg>';
function viewRow(x){return`<div class="item"><label class="check"><input type="checkbox" data-check="${esc(x.id)}" ${done[x.id]?'checked':''}><span>${esc(x.t)}${x.note?`<small>${esc(x.note)}</small>`:''}</span></label>${x.q?`<a target="_blank" rel="noopener" href="${map(x.q)}">Ver mapa</a>`:''}</div>`}
function editRow(x,k){let opts='<option value="">Mover a…</option>'+D.map((d,i)=>i===day?'':`<option value="${i}">${esc(d.s)} · ${esc(d.n)}</option>`).join('');return`<div class="editRow" data-id="${esc(x.id)}"><input data-f="t" value="${esc(x.t)}" placeholder="Actividad"><input data-f="q" value="${esc(x.q)}" placeholder="Lugar para el mapa (opcional)"><input data-f="note" value="${esc(x.note)}" placeholder="Nota (opcional)"><div class="editActions"><button data-a="up" ${k===0?'disabled':''}>↑</button><button data-a="down" ${k===D[day].i.length-1?'disabled':''}>↓</button><select data-a="move">${opts}</select><button class="del ${armed===x.id?'armed':''}" data-a="del">${armed===x.id?'CONFIRMAR':'✕'}</button></div></div>`}
function render(){days.innerHTML=D.map((d,i)=>`<button data-i="${i}" class="${i===day?'on':''}">${esc(d.s)} <span class="dayNum">${11+i}</span></button>`).join('');let d=D[day];if(!editing){daycard.innerHTML=`<div class="planHead"><div><h2>${esc(d.n)}</h2></div><button class="editBtn" id="editBtn" aria-label="Editar itinerario">${gear}</button></div><div>${d.i.map(viewRow).join('')||'<div class="hint">No hay actividades este día.</div>'}</div><div class="saveHint">Marca lo que vayáis haciendo. El progreso se guarda automáticamente en este dispositivo.</div>`}else{daycard.innerHTML=`<div class="planHead"><div class="dayTitleEdit"><input id="dayTitle" value="${esc(d.n)}"></div><button class="editBtn done" id="editBtn">LISTO</button></div><div>${d.i.map(editRow).join('')||'<div class="hint">No hay actividades este día.</div>'}</div><div class="addBox"><input id="newItem" placeholder="Nueva actividad…"><button class="primary" id="addItem">AÑADIR</button></div><div class="saveHint">Puedes editar, reordenar, mover de día o borrar actividades.</div>`}}
load();render();
days.onclick=e=>{let b=e.target.closest('button[data-i]');if(!b)return;day=+b.dataset.i;armed=null;save();render()};
daycard.onclick=e=>{if(e.target.closest('#editBtn')){editing=!editing;armed=null;render();return}if(e.target.id==='addItem'){let inp=$('newItem'),v=inp.value.trim();if(v){D[day].i.push({id:uid(),t:v,q:'',note:''});save();render()}return}let b=e.target.closest('button[data-a]');if(!b)return;let row=b.closest('.editRow'),id=row?.dataset.id,k=D[day].i.findIndex(x=>x.id===id),a=b.dataset.a,L=D[day].i;if(k<0)return;if(a==='up'&&k>0)[L[k-1],L[k]]=[L[k],L[k-1]];else if(a==='down'&&k<L.length-1)[L[k],L[k+1]]=[L[k+1],L[k]];else if(a==='del'){if(armed!==id){armed=id;render();return}else{L.splice(k,1);delete done[id];armed=null}}save();render()};
daycard.onchange=e=>{if(e.target.matches('[data-check]')){let id=e.target.dataset.check;if(e.target.checked)done[id]=1;else delete done[id];save();return}if(e.target.id==='dayTitle'){D[day].n=e.target.value.trim()||D[day].n;save();return}let row=e.target.closest('.editRow');if(!row)return;let k=D[day].i.findIndex(x=>x.id===row.dataset.id);if(k<0)return;let f=e.target.dataset.f,a=e.target.dataset.a;if(f){D[day].i[k][f]=e.target.value.trim();save()}else if(a==='move'&&e.target.value!==''){let x=D[day].i.splice(k,1)[0];D[+e.target.value].i.push(x);save();render()}};
document.querySelector('.tabs').onclick=e=>{let t=e.target.dataset.t;if(!t)return;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('on',b.dataset.t===t));['plan','cambio','frases','curiosidades'].forEach(x=>$(x).classList.toggle('hide',x!==t))};
const P=[['#','Básicas'],['Hola','Cześć','chesh'],['Buenos días / buenas tardes','Dzień dobry','yen dobri'],['Buenas noches','Dobranoc','dobranots'],['Adiós','Do widzenia','do videnia'],['Gracias','Dziękuję','yenkuie'],['Por favor / De nada','Proszę','proshe'],['Perdón','Przepraszam','sheprasham'],['Sí / No','Tak / Nie','tak / nie'],['#','Para entenderse'],['No entiendo','Nie rozumiem','nie rosumiem'],['¿Puede repetir, por favor?','Proszę powtórzyć','proshe poftushich'],['¿Más despacio, por favor?','Proszę mówić wolniej','proshe muvich volnie'],['¿Habla inglés?','Czy mówi pan/pani po angielsku?','chi muvi pan po angielsku'],['¿Habla español?','Czy mówi pan/pani po hiszpańsku?','chi muvi pan po jishpansku'],['#','Comer y pagar'],['Una mesa, por favor','Stolik, proszę','stolik proshe'],['La carta, por favor','Menu, proszę','menu proshe'],['Agua sin gas / con gas','Woda niegazowana / gazowana','voda niegasovana / gasovana'],['Una cerveza, por favor','Piwo, proszę','pivo proshe'],['Está delicioso','Pyszne','pishne'],['La cuenta, por favor','Rachunek, proszę','rajunek proshe'],['¿Cuánto cuesta?','Ile to kosztuje?','ile to koshtuie'],['¿Puedo pagar con tarjeta?','Czy mogę zapłacić kartą?','chi moge zapuachich kartom'],['#','Moverse'],['¿Dónde está…?','Gdzie jest…?','gie yest'],['Izquierda / Derecha / Recto','W lewo / W prawo / Prosto','v levo / v pravo / prosto'],['Estación de tren','Dworzec kolejowy','dvoshets koleiovi'],['Un billete a Varsovia','Bilet do Warszawy','bilet do varshavi'],['¿A qué hora sale el tren?','O której odjeżdża pociąg?','o kturei odiesha pochonk'],['#','Urgencias · teléfono de emergencias: 112'],['¡Ayuda!','Pomocy!','pomotsi'],['Necesito un médico','Potrzebuję lekarza','potshebuie lekasha'],['Farmacia','Apteka','apteka']];
const icons={Básicas:'<svg viewBox="0 0 24 24"><path d="M4 5h16v11H9l-5 4V5Z"/></svg>','Para entenderse':'<svg viewBox="0 0 24 24"><path d="M4 6h10v8H8l-4 3V6Z"/><path d="M14 9h6v8h-3l-3 3"/></svg>','Comer y pagar':'<svg viewBox="0 0 24 24"><path d="M7 3v8M4 3v5c0 2 6 2 6 0V3M7 11v10M16 3v18M16 3c4 2 4 7 0 9"/></svg>',Moverse:'<svg viewBox="0 0 24 24"><path d="M12 21s6-5.4 6-11a6 6 0 1 0-12 0c0 5.6 6 11 6 11Z"/><circle cx="12" cy="10" r="2"/></svg>','Urgencias · teléfono de emergencias: 112':'<svg viewBox="0 0 24 24"><path d="M12 3v18M3 12h18"/></svg>'};
const CAN='speechSynthesis'in window;function speak(t){if(!CAN)return;let u=new SpeechSynthesisUtterance(t);u.lang='pl-PL';u.rate=.82;speechSynthesis.cancel();speechSynthesis.speak(u)}
function renderP(){let h='',open=false;P.forEach((p,i)=>{if(p[0]==='#'){if(open)h+='</div>';h+=`<div class="cat"><div class="cath"><span class="catIcon">${icons[p[1]]||''}</span><span>${p[1]}</span></div>`;open=true}else h+=`<div class="item ph"><div class="phcopy"><span class="es">${p[0]}</span><span class="pl">${p[1]}</span><span class="pron">${p[2]}</span></div>${CAN?`<button class="listen" data-i="${i}">Escuchar</button>`:''}</div>`});if(open)h+='</div>';$('phr').innerHTML=h}
$('phr').onclick=e=>{let b=e.target.closest('.listen');if(b)speak(P[+b.dataset.i][1])};
function conv(a){let r=+rate.value||.23;if(a==='z')eu.value=((+zl.value||0)*r).toFixed(2);else zl.value=((+eu.value||0)/r).toFixed(2);quick();calcTip()}zl.oninput=()=>conv('z');eu.oninput=()=>conv('e');rate.oninput=()=>conv('z');
function quick(){let r=+rate.value||.23;$('quick').innerHTML=[5,10,20,50,100,200].map(z=>`<button class="q" data-z="${z}"><b>${z} zł</b><span>${(z*r).toFixed(2)} €</span></button>`).join('')}$('quick').onclick=e=>{let z=e.target.closest('.q')?.dataset.z;if(z){zl.value=z;conv('z')}};
let tip=10;function fmt(n){return n.toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2})}function calcTip(){let b=+bill.value||0,a=b*tip/100,t=b+a,r=+rate.value||.23;$('tipAmount').innerHTML=fmt(a)+' zł <small>('+fmt(a*r)+' €)</small>';$('tipTotal').innerHTML=fmt(t)+' zł <small>('+fmt(t*r)+' €)</small>'}bill.oninput=calcTip;document.querySelector('.tipBtns').onclick=e=>{let b=e.target.closest('button[data-tip]');if(!b)return;tip=+b.dataset.tip;document.querySelectorAll('.tipBtns button').forEach(x=>x.classList.toggle('on',x===b));calcTip()};
function phonetic(s){let x=String(s).toLowerCase();[['dzię','yen'],['dzie','ye'],['dzi','yi'],['szcz','shch'],['cz','ch'],['sz','sh'],['rz','sh'],['ch','j'],['si','shi'],['ci','chi'],['zi','zhi'],['ni','ñi'],['dz','ds'],['ą','on'],['ę','en'],['ł','u'],['ń','ñ'],['ś','sh'],['ć','ch'],['ź','zh'],['ż','sh'],['w','v'],['j','y'],['ó','u'],['y','i']].forEach(r=>x=x.split(r[0]).join(r[1]));return x.replace(/c/g,'ts').trim()}
async function translate(){let t=trin.value.trim();if(!t)return;trgo.disabled=true;trgo.textContent='Traduciendo…';try{let r=await fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl=es&tl=pl&dt=t&q='+encodeURIComponent(t)),j=await r.json(),pl=j[0].map(x=>x[0]).join(''),known=P.find(p=>p[0]!=='#'&&p[1].toLowerCase()===pl.toLowerCase()),pr=known?known[2]:phonetic(pl);trout.innerHTML=`<div class="result"><div class="pl">${esc(pl)}</div><div class="pronlabel">Pronunciación figurada para español</div><div class="pron">${esc(pr)}</div>${CAN?'<button class="listen" id="trlisten">Escuchar pronunciación</button>':''}</div>`;if($('trlisten'))$('trlisten').onclick=()=>speak(pl)}catch(e){trout.innerHTML='<div class="result">No se pudo traducir ahora.</div>'}finally{trgo.disabled=false;trgo.textContent='Traducir'}}
trgo.onclick=translate;quick();renderP();calcTip();