(()=>{
const C={
'Free tour por Cracovia':'El hejnał de la basílica de Santa María suena desde una de sus torres cada hora, las 24 horas del día, y tiene una peculiaridad que sorprende cuando lo escuchas por primera vez: la melodía se interrumpe bruscamente antes de terminar. La tradición popular cuenta que recuerda a un trompetista medieval que intentó alertar a la ciudad de una invasión tártara y recibió una flecha en la garganta mientras tocaba. Hoy el toque se interpreta cuatro veces, hacia los cuatro puntos cardinales, y el del mediodía se retransmite por la radio polaca.',
'Tarde: plaza, Planty o Wawel':'El dragón de Wawel no es solo una figura simpática colocada para los turistas. La leyenda del Smok Wawelski lleva siglos ligada a Cracovia y cuenta que vivía en una cueva bajo la colina de Wawel y aterrorizaba a sus habitantes hasta que fue derrotado mediante un ingenioso engaño. Junto al Vístula hay actualmente una escultura del dragón que incluso expulsa fuego de verdad cada pocos minutos. La propia cueva situada bajo la colina se conoce como la Guarida del Dragón.',
'Auschwitz I':'El famoso letrero “Arbeit macht frei” de la entrada de Auschwitz I fue robado durante la madrugada del 18 de diciembre de 2009. Los ladrones lo cortaron en tres partes para poder transportarlo, pero la policía polaca consiguió recuperarlo apenas tres días después. Debido a su enorme valor histórico y a los daños sufridos, el original se conserva protegido por el museo. Por eso, aunque parezca exactamente el mismo, el letrero que hoy atraviesas al entrar en el recinto es una réplica.',
'Birkenau (Auschwitz II)':'La imagen de los trenes entrando bajo la gran torre de Birkenau es hoy inseparable del campo, pero durante buena parte de su funcionamiento los convoyes no llegaban hasta ese punto. El ramal ferroviario que penetraba directamente en Birkenau fue construido en la primavera de 1944, coincidiendo con las deportaciones masivas de judíos húngaros. Antes, muchos deportados descendían de los trenes en una zona exterior conocida como la Judenrampe y desde allí eran conducidos al complejo.',
'Paseo por el centro de Varsovia':'Cuando paseas por el casco antiguo de Varsovia parece que estás viendo una ciudad de varios siglos de antigüedad, pero gran parte de lo que te rodea fue reconstruido después de 1945. Tras el Levantamiento de Varsovia de 1944, más del 85 % del centro histórico quedó destruido. La reconstrucción fue extraordinariamente minuciosa y utilizó planos, fotografías, fragmentos recuperados e incluso antiguas pinturas para recuperar su aspecto. La UNESCO acabó reconociendo precisamente esa reconstrucción casi total como un ejemplo excepcional en la historia de la conservación.',
'Parque Łazienki / Ciudad Nueva':'El nombre Łazienki significa literalmente “baños” y no tiene nada que ver con los lagos del parque. Procede de un antiguo pabellón de baños construido en el siglo XVII que, tras sucesivas transformaciones, terminó integrado en el actual Palacio sobre la Isla. Hay además unos habitantes que suelen robar bastante protagonismo a los monumentos: pavos reales que pasean libremente y ardillas sorprendentemente confiadas. El parque fue residencia de verano del último rey de Polonia, Estanislao II Augusto.',
'Calle Nowy Świat':'Nowy Świat significa “Nuevo Mundo”, pero la calle está muy lejos de ser nueva. Forma parte de la histórica Ruta Real de Varsovia, el gran eje que comunicaba el Castillo Real con residencias situadas al sur de la ciudad. Durante la Segunda Guerra Mundial muchos de sus edificios quedaron destruidos y, al reconstruirla, se decidió recuperar en buena medida un aspecto anterior y más clásico en lugar de reproducir exactamente las fachadas que tenía justo antes de la guerra. Por eso su imagen actual es, en cierto modo, una interpretación histórica deliberada.',
'Tour comunista por Varsovia':'El enorme reloj del Palacio de la Cultura y la Ciencia no formaba parte del edificio original de los años cincuenta. Fue instalado medio siglo después y comenzó a funcionar durante la Nochevieja de 2000 a 2001. Sus cuatro esferas tienen unos 6 metros de diámetro y están colocadas a gran altura en la torre, mientras que el popular mirador del piso 30 se encuentra a unos 114 metros. El edificio sigue provocando opiniones muy enfrentadas en Varsovia por su origen como “regalo” de la Unión Soviética durante la época de Stalin.',
'Barrio de Praga':'Si entras en algunos patios antiguos de Praga puedes encontrar pequeños altares con imágenes religiosas, flores y figuras de la Virgen. No son una decoración reciente: en el distrito sobreviven alrededor de un centenar de estos santuarios vecinales y muchos aparecieron durante la ocupación alemana, cuando desplazarse hasta una iglesia podía resultar difícil o peligroso. Los vecinos utilizaban los patios como pequeños lugares comunitarios de oración. Es uno de esos detalles fáciles de pasar por alto y que cuentan una parte muy íntima de la historia del barrio.',
'Kazimierz':'Kazimierz no nació como un barrio de Cracovia. El rey Casimiro III el Grande fundó allí una ciudad independiente en el siglo XIV, con su propia plaza de mercado y una identidad diferenciada, y no quedó incorporada administrativamente a Cracovia hasta siglos después. Su antiguo mercado era enorme, de aproximadamente 195 por 195 metros, y por la zona atravesaba una importante ruta comercial relacionada con la sal procedente de Wieliczka y Bochnia. Esa antigua estructura urbana todavía ayuda a explicar por qué Kazimierz se siente diferente al casco histórico.',
'Podgórze':'En pleno gueto de Cracovia hubo una farmacia cuyo propietario no judío decidió permanecer allí: la Farmacia del Águila, dirigida por Tadeusz Pankiewicz. Él y su personal fueron testigos directos de las deportaciones y ayudaron clandestinamente a habitantes del gueto proporcionando medicamentos y otros recursos. Pankiewicz dejó posteriormente un valioso testimonio escrito sobre lo que había presenciado. El establecimiento original, situado en la actual Plaza de los Héroes del Gueto, forma hoy parte del Museo de Cracovia.',
'Fábrica de Schindler':'La fábrica asociada a Oskar Schindler ya existía antes de que él llegara a Cracovia. Se llamaba “Rekord” y había sido fundada en 1937 por tres empresarios judíos, pero atravesó problemas económicos poco antes de la ocupación alemana. Schindler se hizo cargo de ella y pasó a llamarse Deutsche Emailwarenfabrik, dedicada principalmente a productos esmaltados y posteriormente a producción para el ejército alemán. La exposición actual, además, no se centra únicamente en Schindler: cuenta sobre todo cómo era la vida en Cracovia durante la ocupación nazi.',
'Lonja de los Paños':'Cuando pases bajo los soportales de la Sukiennice busca un gran cuchillo de hierro colgado en uno de ellos. Existe desde hace mucho tiempo y alrededor de él surgió una leyenda bastante macabra: dos hermanos habrían construido las dos torres de la basílica de Santa María y, al ver uno que la torre de su hermano iba a superarle, lo asesinó con ese cuchillo. Atormentado por lo ocurrido, después se habría quitado la vida. La historia es legendaria, pero el cuchillo sigue allí y mucha gente cruza la Lonja sin reparar en él.',
'Minas de sal de Wieliczka':'La espectacular capilla de Santa Kinga se encuentra a más de 100 metros bajo tierra y parece una iglesia construida con materiales normales hasta que empiezas a fijarte en los detalles: altares, relieves, esculturas e incluso elementos decorativos fueron tallados en sal por los propios mineros. Su creación se prolongó durante décadas. Entre los relieves hay incluso una versión de “La última cena” de Leonardo da Vinci realizada en la pared de sal, con una profundidad sorprendentemente pequeña para el efecto tridimensional que consigue.'
};
const css=document.createElement('style');css.textContent='.infoCuriosity{margin-top:14px;padding:13px 14px;border-radius:14px;background:#f4eee3;border:1px solid #e4d8c8;color:#4f5c56;font-size:1.02rem;line-height:1.58}.infoCuriosity b{display:block;margin-bottom:5px;color:#7f1d1d;font-size:.8rem;letter-spacing:.08em;text-transform:uppercase}';document.head.appendChild(css);
function put(key){const m=document.getElementById('infoModal');if(!m||!C[key])return;const body=m.querySelector('.infoBody');if(!body)return;body.querySelector('.infoCuriosity')?.remove();const box=document.createElement('div');box.className='infoCuriosity';box.innerHTML='<b>💡 ¿Sabías que…?</b><span></span>';box.querySelector('span').textContent=C[key];const tip=body.querySelector('.infoTip');tip?body.insertBefore(box,tip):body.appendChild(box)}
document.addEventListener('click',e=>{const b=e.target.closest('.infoBtn');if(!b)return;setTimeout(()=>put(b.dataset.info),0)},true);
})();