(()=>{
const css=`
.quickAddPlan{margin:14px 0 4px;width:100%;border:1px dashed rgba(127,29,29,.42);background:rgba(127,29,29,.055);color:#7f1d1d;border-radius:14px;padding:12px 14px;font:700 12px/1 system-ui;letter-spacing:.04em}
.homeBtn{display:flex;align-items:center;justify-content:center;gap:8px;margin:12px 0 14px;width:100%;box-sizing:border-box;border:1px solid rgba(127,29,29,.18);background:#fff;color:#7f1d1d;border-radius:14px;padding:12px 14px;text-decoration:none;font:800 12px/1 system-ui;letter-spacing:.025em;box-shadow:0 3px 12px rgba(70,45,30,.05)}
.homeBtn:active{transform:scale(.985)}
.quickPlanModal{position:fixed;inset:0;z-index:10000;display:none;align-items:flex-end;justify-content:center}.quickPlanModal.show{display:flex}.quickPlanBack{position:absolute;inset:0;background:rgba(20,18,15,.48);backdrop-filter:blur(3px)}.quickPlanSheet{position:relative;width:min(100%,560px);background:#f8f4eb;border-radius:22px 22px 0 0;padding:22px 18px calc(20px + env(safe-area-inset-bottom));box-shadow:0 -12px 40px rgba(0,0,0,.18)}.quickPlanSheet h2{margin:0 38px 5px 0;font-size:23px}.quickPlanSheet p{margin:0 0 16px;color:#777;font-size:13px}.quickPlanClose{position:absolute;right:16px;top:14px;border:0;background:#e8e2d7;width:34px;height:34px;border-radius:50%;font-size:22px}.quickPlanSheet label{display:block;margin:12px 0 5px;font-size:11px;font-weight:800;letter-spacing:.05em;text-transform:uppercase;color:#7f1d1d}.quickPlanSheet input,.quickPlanSheet select{box-sizing:border-box;width:100%;border:1px solid #d9d1c5;background:white;border-radius:12px;padding:12px;font:15px system-ui;color:#222}.quickPlanSave{width:100%;margin-top:18px;border:0;border-radius:13px;background:#7f1d1d;color:white;padding:13px;font-weight:800;letter-spacing:.04em}.quickPlanError{min-height:16px;margin-top:8px;color:#9b1c1c;font-size:12px}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
const HOME={krakow:'https://maps.app.goo.gl/bCSbuMTGcPTZRMXf9?g_st=iw',warsaw:'https://maps.app.goo.gl/u6ujwKst3Gifm5BMA?g_st=iw'};
function cityForDay(){const n=(D?.[day]?.n||'').toLowerCase();if(n.includes('varsovia')&&!n.includes('→ cracovia'))return'warsaw';if(n.includes('auschwitz'))return'krakow';if(n.includes('cracovia → varsovia'))return'warsaw';return'krakow'}
function addHomeButton(){const card=document.getElementById('daycard');if(!card||card.querySelector('.homeBtn')||typeof editing!=='undefined'&&editing)return;const head=card.querySelector('.planHead');if(!head)return;const city=cityForDay();const a=document.createElement('a');a.className='homeBtn';a.href=HOME[city];a.target='_blank';a.rel='noopener';a.textContent='⌂  VOLVER AL ALOJAMIENTO';head.insertAdjacentElement('afterend',a)}
function modal(){if(document.getElementById('quickPlanModal'))return;const m=document.createElement('div');m.id='quickPlanModal';m.className='quickPlanModal';m.innerHTML=`<div class="quickPlanBack" data-qclose></div><div class="quickPlanSheet"><button class="quickPlanClose" data-qclose>×</button><h2>Añadir plan</h2><p>Añádelo al día que quieras del viaje.</p><label>Día</label><select id="quickPlanDay"></select><label>Plan</label><input id="quickPlanName" maxlength="100" placeholder="Ej. Tomar algo en…"><label>Lugar para el mapa · opcional</label><input id="quickPlanPlace" maxlength="160" placeholder="Nombre o dirección"><label>Nota · opcional</label><input id="quickPlanNote" maxlength="160" placeholder="Hora, reserva, recordatorio…"><button class="quickPlanSave" id="quickPlanSave">AÑADIR AL ITINERARIO</button><div class="quickPlanError" id="quickPlanError"></div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target.closest('[data-qclose]'))close()});}
function open(){modal();const m=document.getElementById('quickPlanModal'),sel=document.getElementById('quickPlanDay');sel.innerHTML=D.map((d,i)=>`<option value="${i}" ${i===day?'selected':''}>${d.s} · ${d.n}</option>`).join('');document.getElementById('quickPlanName').value='';document.getElementById('quickPlanPlace').value='';document.getElementById('quickPlanNote').value='';document.getElementById('quickPlanError').textContent='';m.classList.add('show');setTimeout(()=>document.getElementById('quickPlanName').focus(),100)}
function close(){document.getElementById('quickPlanModal')?.classList.remove('show')}
function addButton(){const card=document.getElementById('daycard');if(!card||card.querySelector('.quickAddPlan')||typeof editing!=='undefined'&&editing)return;const hint=card.querySelector('.saveHint');const b=document.createElement('button');b.type='button';b.className='quickAddPlan';b.textContent='+ AÑADIR PLAN IMPROVISADO';b.onclick=open;hint?card.insertBefore(b,hint):card.appendChild(b)}
const originalRender=window.render;if(typeof originalRender==='function'){window.render=function(){originalRender();setTimeout(()=>{addHomeButton();addButton()},0)}}
document.addEventListener('click',e=>{if(e.target.id!=='quickPlanSave')return;const name=document.getElementById('quickPlanName').value.trim(),place=document.getElementById('quickPlanPlace').value.trim(),note=document.getElementById('quickPlanNote').value.trim(),di=+document.getElementById('quickPlanDay').value;if(!name){document.getElementById('quickPlanError').textContent='Escribe el nombre del plan.';return}if(!D[di])return;D[di].i.push({id:uid(),t:name,q:place,note});save();if(di===day)render();close()});
setTimeout(()=>{addHomeButton();addButton()},0);
})();