/* Fichas verificadas de las reservas. Sin datos personales, PIN ni códigos de acceso. */
(() => {
const records=[
{day:0,match:/free tour/i,title:'Free Tour · casco antiguo',date:'Domingo 11 de octubre',time:'10:30',detail:['8 adultos · Español · GuruWalk / Krakow Explorers','Encuentro: Rynek Główny 4, frente a la Basílica de Santa María.','Busca el paraguas naranja de Krakow Explorers.','Presentar el QR de confirmación al guía.'],map:'Rynek Główny 4, Kraków'},
{day:1,match:/Auschwitz I|Birkenau/i,title:'Auschwitz-Birkenau',date:'Lunes 12 de octubre',time:'09:30 (por confirmar)',detail:['8 adultos · Visita en español','Encuentro previsto: Cracow City Tours, Plac Jana Matejki 2, Cracovia.','Llegar 15 minutos antes de la hora confirmada.','Llevar DNI o pasaporte físico; equipaje máximo 30 × 20 × 10 cm.','El proveedor puede modificar hora y punto de encuentro: revisar el aviso del día anterior.'],map:'Plac Jana Matejki 2, Kraków'},
{day:2,match:/Tren Cracovia/i,title:'Tren Cracovia → Varsovia',date:'Martes 13 de octubre',time:'09:01 → 11:20',detail:['PKP Intercity · Tren 3106 · Vagón 1 · Primera clase','8 viajeros, dos billetes: 2 y 6 plazas.','Asientos: 61, 62, 63, 64, 65, 66, 73 y 75.','Salida: Kraków Główny. Llegada: Warszawa Centralna.','Comprobar el andén en la estación.'],map:'Kraków Główny, Kraków'},
{day:3,match:/Tren Varsovia/i,title:'Tren Varsovia → Cracovia',date:'Miércoles 14 de octubre',time:'17:40 → 19:56',detail:['PKP Intercity · Tren 5306 · Vagón 4 · Segunda clase','8 viajeros, dos billetes: 2 y 6 plazas.','Asientos: 34, 36, 72, 74, 75, 76, 77 y 78.','Salida: Warszawa Centralna. Llegada: Kraków Główny.','Tres tarifas sénior: llevar documentación que acredite la edad.'],map:'Warszawa Centralna, Warszawa'},
{day:4,match:/Comer en Starka/i,title:'Comida · Starka',date:'Jueves 15 de octubre',time:'14:00–16:00',detail:['Reserva confirmada para 8 personas.','Józefa 14, Cracovia.','La mesa se mantiene hasta 15 minutos después de la hora reservada.','Después tenéis Schindler a las 17:10.'],map:'Starka, Józefa 14, Kraków'},
{day:4,match:/Fábrica de Schindler/i,title:'Fábrica de Schindler',date:'Jueves 15 de octubre',time:'17:10',detail:['8 entradas nominativas · Exposición permanente.','Lipowa 4, Cracovia.','Llevar documento físico de identidad: las entradas son nominativas.','Dos PDF: uno con 3 entradas y otro con 5.'],map:'Fabryka Emalia Oskara Schindlera, Lipowa 4, Kraków'},
{day:5,match:/Minas de sal/i,title:'Minas de sal de Wieliczka',date:'Viernes 16 de octubre',time:'14:45 (puede variar)',detail:['GetYourGuide · Super Cracow · Visita en español.','Duración estimada: 4 h 30 min.','ATENCIÓN: el PDF no confirma punto de encuentro o recogida. Contactar al proveedor y confirmar al menos 24 horas antes.','Temperatura: 14–16 °C. Llevar abrigo y calzado cómodo.','Unos 800 escalones, 350 al inicio. No llevar maletas grandes.'],map:''},
{day:6,match:/Cena en Morskie Oko/i,title:'Cena · Morskie Oko',date:'Sábado 17 de octubre',time:'19:30–21:30',detail:['Reserva confirmada para 8 personas.','La mesa está disponible durante 2 horas.','Tolerancia de llegada: 15 minutos, hasta las 19:45.'],map:'Morskie Oko, Kraków'}
];
const style=document.createElement('style');style.textContent=`.bookingBtn{margin:5px 0 5px 9px;padding:8px 11px;border:1px solid #b87973;border-radius:11px;background:#fff4f1;color:#823c37;font-weight:700;font-size:13px;cursor:pointer}.bookingOverlay{position:fixed;inset:0;z-index:2000;background:rgba(20,20,25,.66);display:flex;align-items:flex-end;justify-content:center}.bookingSheet{box-sizing:border-box;width:100%;max-width:550px;max-height:85dvh;overflow:auto;background:#fffaf6;color:#242424;border-radius:24px 24px 0 0;padding:24px 22px calc(28px + env(safe-area-inset-bottom))}.bookingSheet h2{margin:0 0 8px;font-size:23px}.bookingSheet ul{padding-left:20px;line-height:1.6}.bookingSheet li{margin-bottom:8px}.bookingSheet .bookingTime{font-size:19px;font-weight:800;color:#9d4441}.bookingSheet .bookingActions{display:flex;gap:10px;flex-wrap:wrap}.bookingSheet .bookingActions a,.bookingSheet .bookingActions button{border-radius:12px;border:1px solid #d8bbb5;padding:11px 16px;background:#f4e4df;color:#5e2827;text-decoration:none;font-weight:700}.bookingSheet .bookingNote{font-size:13px;color:#695f5d;margin-top:18px}`;document.head.append(style);
function open(r){document.querySelector('.bookingOverlay')?.remove();const ov=document.createElement('div');ov.className='bookingOverlay';const sheet=document.createElement('div');sheet.className='bookingSheet';const h=document.createElement('h2');h.textContent=r.title;sheet.append(h);const date=document.createElement('p');date.textContent=r.date;sheet.append(date);const time=document.createElement('p');time.className='bookingTime';time.textContent=r.time;sheet.append(time);const ul=document.createElement('ul');r.detail.forEach(t=>{const li=document.createElement('li');li.textContent=t;ul.append(li)});sheet.append(ul);const actions=document.createElement('div');actions.className='bookingActions';if(r.map){const a=document.createElement('a');a.href='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(r.map);a.target='_blank';a.rel='noopener';a.textContent='Ver mapa';actions.append(a)}const close=document.createElement('button');close.textContent='Cerrar';close.onclick=()=>ov.remove();actions.append(close);sheet.append(actions);const note=document.createElement('p');note.className='bookingNote';note.textContent='Los PDF y códigos QR originales estarán disponibles cuando se habilite el almacenamiento familiar privado. No se han publicado en abierto.';sheet.append(note);ov.append(sheet);ov.onclick=e=>{if(e.target===ov)ov.remove()};document.addEventListener('keydown',function escape(e){if(e.key==='Escape'){ov.remove();document.removeEventListener('keydown',escape)}});document.body.append(ov)}
function decorate(){const card=document.getElementById('daycard');if(!card||typeof day==='undefined'||typeof editing!=='undefined'&&editing)return;const list=records.filter(r=>r.day===day);card.querySelectorAll('.item').forEach(item=>{const label=item.querySelector('label.check span');if(!label)return;const t=label.firstChild?.textContent||'';const r=list.find(x=>x.match.test(t));if(!r||item.querySelector('.bookingBtn'))return;const btn=document.createElement('button');btn.type='button';btn.className='bookingBtn';btn.textContent='Reserva · detalles';btn.onclick=()=>open(r);item.append(btn)})}
const root=document.getElementById('daycard');if(root){new MutationObserver(()=>decorate()).observe(root,{childList:true});decorate()}
})();